---
# This dpkg configuration file is present in container images downloaded from
# hub.nspawn.io to exclude all docs from packages, including manpages. It is
# removed so slurm and friends manpages can be installed.
- name: Remove dpkg config to exclude docs
  ansible.builtin.file:
    path: /etc/dpkg/dpkg.cfg.d/01_nodoc
    state: absent

# Ensure APT repositories metadata is updated
- name: Update apt repository metadata
  ansible.builtin.apt:
    update_cache: yes
