---
# This dpkg configuration file is present in container images downloaded from
# hub.nspawn.io to exclude all docs from packages, including manpages. It is
# removed so slurm and friends manpages can be installed.
- name: Remove dpkg config to exclude docs
  ansible.builtin.file:
    path: /etc/dpkg/dpkg.cfg.d/01_nodoc
    state: absent

# Add hpck.it deb packages repositories
- name: Add HPCk.it deb packages repository
  block:

    - name: Download HPCk.it packages repository keyring
      ansible.builtin.get_url:
        url: https://hpck.it/keyring.asc
        dest: /usr/share/keyrings/hpckit.asc

    - name: Add HPCk.it repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hpckit.asc arch=amd64] https://hpck.it/deb {{ ansible_distribution_release }} {{ common_hpckit_derivatives|join(' ') }}"
        state: present
        filename: hpckit

# Add Rackslab development deb packages repositories
- name: Add Rackslab development deb packages repository
  block:

    - name: Download Rackslab development packages repository keyring
      ansible.builtin.get_url:
        url: https://build.rackslab.io/devs/keyring.asc
        dest: /usr/share/keyrings/devs.asc

    - name: Add Rackslab development repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/devs.asc arch=amd64] https://build.rackslab.io/devs/deb {{ ansible_distribution_release }} {{ common_devs_derivatives|join(' ') }}"
        state: present
        filename: devs

  when: common_with_devs_repos
