---
- name: Define system locale
  ansible.builtin.command:
    argv:
      - /usr/bin/localectl
      - set-locale
      - LANG=en_US.UTF-8
    creates: /etc/locale.conf

# On redhat based distributions, add EPEL repos GPG key and yum conf using
# release package
- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: Install EPEL repository
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

# CR/PowerTools repo is required to install Slurm packages dependencies.
- name: Enable CR repository
  ansible.builtin.command:
    argv:
      - /usr/bin/dnf
      - config-manager
      - --set-enabled
      - crb
  when: ansible_distribution_major_version == "9"

- name: Enable PowerTools repository
  ansible.builtin.command:
    argv:
      - /usr/bin/dnf
      - config-manager
      - --set-enabled
      - powertools
  when: ansible_distribution_major_version == "8"

# Add hpck.it RPM packages repositories
- name: Add HPCk.it rpm packages repository
  ansible.builtin.yum_repository:
    name: "hpck.it-{{ item }}"
    description: "HPCk.it {{ item }} derivative repository"
    file: hpckit
    baseurl: "https://hpck.it/rpm/el$releasever/{{ item }}/$basearch/"
    gpgcheck: yes
    gpgkey: https://hpck.it/keyring.asc
  loop: "{{ common_hpckit_derivatives }}"

# Add Rackslab development deb packages repositories
- name: Add Rackslab development rpm packages repository
  ansible.builtin.yum_repository:
    name: "Rackslab-devs-{{ item }}"
    description: "Rackslab development {{ item }} repository"
    file: rackslab-devs
    baseurl: "https://build.rackslab.io/devs/rpm/el$releasever/{{ item }}/$basearch/"
    gpgcheck: yes
    gpgkey: https://build.rackslab.io/devs/keyring.asc
  when: common_with_devs_repos
  loop: "{{ common_devs_derivatives }}"
