---
- name: Define system locale
  ansible.builtin.command:
    argv:
      - /usr/bin/localectl
      - set-locale
      - LANG=en_US.UTF-8
    creates: /etc/locale.conf

# On redhat based distributions, add EPEL repos GPG key and yum conf using
# release package
- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: Install EPEL repository
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

# CR/PowerTools repo is required to install Slurm packages dependencies.
- name: Enable CR repository
  ansible.builtin.command:
    argv:
      - /usr/bin/dnf
      - config-manager
      - --set-enabled
      - crb
  when: ansible_distribution_major_version == "9"

- name: Enable PowerTools repository
  ansible.builtin.command:
    argv:
      - /usr/bin/dnf
      - config-manager
      - --set-enabled
      - powertools
  when: ansible_distribution_major_version == "8"
