---
# On redhat based distributions, add EPEL repos GPG key and yum conf using
# release package
- name: Import EPEL GPG key
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    state: present

- name: Install EPEL repository
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

# PowerTools repo is required to install Slurm packages dependencies.
- name: Enable PowerTools repo
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    regexp: '^enable='
    line: enabled=1
