---
- name: Define openldap server organization domain
  ansible.builtin.debconf:
    name: slapd
    question: "slapd/domain"
    value: "{{ ldap_server_domain }}"
    vtype: string

- name: Define openldap server administration password
  ansible.builtin.debconf:
    name: slapd
    question: "{{ item }}"
    value: "{{ ldap_server_admin_password }}"
    vtype: password
  loop:
  - slapd/password1
  - slapd/password2
  when: ldap_profile

- name: Install openldap server packages
  ansible.builtin.package:
    name: "{{ ldap_server_packages }}"
    state: latest
  register: ldap_server_packages_installation

- name: Generate bootstrap LDIF
  ansible.builtin.template:
    src: bootstrap.ldif.j2
    dest: "{{ ldap_server_ldif_path }}"
    owner: "{{ ldap_server_system_user }}"
    group: "{{ ldap_server_system_group }}"
    mode: '0600'
  when: ldap_server_packages_installation is changed

- name: Insert boostrap LDIF in LDAP directory
  become: true
  become_method: su
  # shell of ldap system user is disabled, flag is used to force real shell
  become_flags: '-s /bin/sh'
  become_user: "{{ ldap_server_system_user }}"
  ansible.builtin.command:
    cmd: "/usr/sbin/slapadd -v -l {{ ldap_server_ldif_path }}"
  when: ldap_server_packages_installation is changed
