- hosts: all
  remote_user: root
  roles:
    - common
    - { role: ldap, when: "'admin' in group_names" }
    - sssd
    - { role: users, when: "'login' in group_names" }
    - slurm
    - { role: mpi, when: mpi_nodes }
