---
slurm_profiles: {}
slurm_emulator: False
slurm_with_accounting: true
slurm_with_munge: false
slurm_with_gres_gpu: false
slurm_gpus_models_map: {}
slurm_uid: 432  # picked randomly among 100-499
slurm_gid: 432  # picked randomly among 100-499
slurmrestd_uid: 433  # picked randomly among 100-499
slurmrestd_gid: 433  # picked randomly among 100-499
slurm_server: admin
slurm_cluster: hpc
slurm_local_munge_key_file: munge.key  # dummy
slurm_local_slurm_key_file: slurm.key  # dummy
slurm_local_mariadb_password_file: mariadb.password  # dummy
slurm_local_jwt_key_file: jwt_hs256.key  # dummy
# The lookup errors are ignored because the variable is loaded by boostrap
# tasks file (in bootstrap playbook) before it generates the file. This way, a
# warning is displayed but Ansible continues instead of failing with the error.
slurm_db_password: "{{ lookup('file', slurm_local_mariadb_password_file, errors='ignore') }}"
slurm_with_db_archive: true
slurm_db_archive_dir: /var/lib/slurm/slurmdbd
slurm_db_purge_after: 14days
slurm_users: []
slurm_accounts: []
slurm_qos: []
slurm_compute_nodes: []
slurm_partitions:
- name: normal
  nodes: "{{ slurm_compute_nodes | map(attribute='nodes') | flatten | nodeset_fold }}"
  default: yes
  params:
    MaxTime: INFINITE
    State: UP

slurm_params: {}
slurmdbd_params: {}

# When disabled, slurm REST API service is not deployed.
slurm_with_slurmrestd: True
# When disabled, slurmrestd fallback to local authentication on unix socket and
# authentication on other daemons is based on munge only.
slurm_with_jwt: True
slurm_restd_with_unix_socket: False
slurm_restd_socket: /run/slurmrestd/slurmrestd.socket
slurm_restd_port: 6820
slurm_restd_service_override_path: /etc/systemd/system/slurmrestd.service.d/firehpc.conf
