---
- name: Gather OS specific variables
  ansible.builtin.include_vars:
    file: "os/{{ ansible_facts.os_family | lower }}.yml"

- name: Install OpenMPI
  ansible.builtin.package:
    name: "{{ mpi_packages }}"
    state: latest
