---
- name: Create slurmd spool directory
  ansible.builtin.file:
    path: "{{ slurm_slurmd_spool_dir }}"
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: Install slurm compute specific packages
  ansible.builtin.package:
    name: "{{ slurm_emulator | ternary(slurm_emulator_compute_packages, slurm_compute_packages) }}"
    state: latest

# This is required on redhat based distributions as the service is not
# automatically started by the RPM packages, and it does not hurt on Debian.
- name: Ensure slurmd service is started
  ansible.builtin.service:
    name: slurmd
    state: started
    enabled: yes
