---
- name: Create slurmctld state directory
  ansible.builtin.file:
    path: "{{ slurm_state_save_loc }}"
    state: directory
    owner: slurm
    group: slurm
    mode: '0700'

- name: Deploy slurmdbd configuration file
  ansible.builtin.template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: slurm
    mode: '0600'
  notify: Restart slurmdbd
  when: slurm_with_accounting

- name: Install slurm server specific packages
  ansible.builtin.package:
    name: "{{ slurm_emulator | ternary(slurm_emulator_server_packages, slurm_server_packages) }}"
    state: latest

- name: Install slurm accounting specific packages
  ansible.builtin.package:
    name: "{{ slurm_emulator | ternary(slurm_emulator_accounting_packages, slurm_accounting_packages) }}"
    state: latest
  when: slurm_with_accounting

- name: Install slurmrestd
  ansible.builtin.package:
    name: "{{ slurm_emulator | ternary(slurm_emulator_server_packages, slurm_restd_packages) }}"
    state: latest
  when: slurm_with_slurmrestd

# The slurm JWT signing key must be deployed early because it is referenced in
# slurm.conf and slurmdbd.conf and its presence is required for these daemons to
# start properly.
- name: Deploy slurm JWT signing key
  ansible.builtin.copy:
    src: "{{ slurm_local_jwt_key_file }}"
    dest: "{{ slurm_jwt_key_path }}"
    owner: slurm
    group: slurm
    mode: 0400
  when:
  - slurm_with_slurmrestd
  - slurm_with_jwt

# This is required on redhat based distributions as the service is not
# automatically started by the RPM packages, and it does not hurt on Debian.
- name: Ensure slurm server service is started
  ansible.builtin.service:
    name: slurmctld
    state: started
    enabled: yes

- name: Ensure slurm accounting service is started
  ansible.builtin.service:
    name: slurmdbd
    state: started
    enabled: yes
  when: slurm_with_accounting

- name: Create slurmdbd archive directory
  ansible.builtin.file:
    path: "{{ slurm_db_archive_dir }}"
    state: directory
    owner: slurm
    group: slurm
    mode: 0755
  when:
  - slurm_with_accounting
  - slurm_with_db_archive

- name: Create slurmrestd service override directory
  ansible.builtin.file:
    path: "{{ slurm_restd_service_override_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: slurm_with_slurmrestd

- name: Deploy slurmrestd service override file
  ansible.builtin.template:
    src: slurmrestd.service.j2
    dest: "{{ slurm_restd_service_override_path }}"
    owner: slurm
    group: slurm
    mode: 0644
  notify: Restart slurmrestd
  when: slurm_with_slurmrestd

- name: Ensure slurmrestd service is started
  ansible.builtin.systemd:
    name: slurmrestd
    state: started
    enabled: yes
    daemon_reload: yes
  when: slurm_with_slurmrestd

- name: Create cluster in slurmdbd
  ansible.builtin.command:
    cmd: "sacctmgr --immediate create cluster {{ slurm_cluster }}"
    creates: "/var/lib/mysql/slurm_acct_db/{{ slurm_cluster }}_job_table.ibd"
  # On recent versions of Slurm, the cluster is automatically created as soon as
  # slurmctld registers to slurmdbd, then ignore the creation error.
  ignore_errors: true
  when: slurm_with_accounting

- name: Get current slurmdbd accounts
  ansible.builtin.command:
    cmd: sacctmgr --noheader --parsable2 list accounts format=Account
  register: slurmdbd_accounts
  when: slurm_with_accounting

- name: Create account in slurmdbd
  ansible.builtin.command:
    cmd: "sacctmgr --immediate create account name={{ item.name }} cluster={{ slurm_cluster }} parent={{ item.parent }}"
  when:
  - slurm_with_accounting
  - item.name not in slurmdbd_accounts.stdout_lines
  loop: "{{ slurm_accounts }}"

- name: Get current slurmdbd users
  ansible.builtin.command:
    cmd: sacctmgr --noheader --parsable2 list users format=User
  register: slurmdbd_users
  when: slurm_with_accounting

- name: Create users in slurmdbd
  ansible.builtin.command:
    cmd: "sacctmgr --immediate create user name={{ item }} cluster={{ slurm_cluster }} account={{ slurm_accounts | selectattr('members', 'search', item) | map(attribute='name') | last }}"
  when:
  - slurm_with_accounting
  - item not in slurmdbd_users.stdout_lines
  loop: "{{ slurm_users }}"

- name: Get current slurmdbd QOS
  ansible.builtin.command:
    cmd: sacctmgr --noheader --parsable2 list qos format=name
  register: slurmdbd_qos
  when: slurm_with_accounting

- name: Create QOS in slurmdbd
  ansible.builtin.command:
    cmd: "sacctmgr --immediate create qos {{ item.name }} {{ item.args | join(' ') }}"
  when:
  - slurm_with_accounting
  - item.name not in slurmdbd_qos.stdout_lines
  loop: "{{ slurm_qos }}"

- name: Allow QOS to root association in slurmdbd
  ansible.builtin.command:
    cmd: "sacctmgr --immediate update account root set qos+={{ item.name }}"
  when:
  - slurm_with_accounting
  - item.name not in slurmdbd_qos.stdout_lines
  loop: "{{ slurm_qos }}"
