---
- name: Install sssd packages
  ansible.builtin.package:
    name: "{{ sssd_packages }}"
    state: latest

- name: Deploy sssd service configuration file
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: "/etc/sssd/sssd.conf"
    owner: root
    group: root
    mode: 0600
  notify: Restart sssd
