- hosts: localhost
  vars:
    ssh_key_dir: '../ssh'
  tasks:
  - name: Generate specific SSH files
    import_role:
      name: ssh
      tasks_from: localkeys

- hosts: all
  vars:
    ssh_key_dir: '../ssh'
  roles:
    - common
    - ssh
