- hosts: all
  remote_user: root
  roles:
    - role: common
      tags: [ common ]
    - role: ldap
      when: "'admin' in group_names"
      tags: [ ldap ]
    - role: sssd
      tags: [ sssd ]
    - role: users
      when: "'login' in group_names"
      tags: [ users ]
    - role: slurm
      tags: [ slurm ]
    - role: slurmweb
      when:
      - "'admin' in group_names"
      - slurmweb_enabled
      tags: [ slurmweb ]
    - role: mpi
      when: mpi_nodes
      tags: [ mpi ]
