- hosts: localhost
  vars:
    ssh_dir: '../ssh'
  tasks:
  - name: Create SSH hosts keys directory
    ansible.builtin.file:
      path: "{{ ssh_dir }}/hosts/{{item}}"
      state: directory
      recurse: true
    with_items: "{{ groups['all'] }}"
  - name: Generate SSH hosts RSA keys
    community.crypto.openssh_keypair:
      path: "{{ ssh_dir }}/hosts/{{ item.0 }}/ssh_host_{{ item.1 }}_key"
      type: "{{ item.1 }}"
    loop: "{{ groups['all'] | product(['rsa', 'dsa', 'ecdsa', 'ed25519']) | list }}"
  - name: Generate SSH known_host
    ansible.builtin.known_hosts:
      path: "{{ ssh_dir }}/known_hosts"
      name: "{{ item.0 }}"
      key: "{{ item.0 }} {{ lookup('file', '{{ ssh_dir }}/hosts/{{ item.0 }}/ssh_host_{{ item.1 }}_key.pub') }}"
    loop: "{{ groups['all'] | product(['rsa', 'dsa', 'ecdsa', 'ed25519']) | list }}"

- hosts: all
  tasks:
  - name: Set a hostname specifying strategy
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
      use: systemd
  - name: Ensure basic packages are installed and updated
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - neovim
      - htop
      - gpg
      - curl
      - rsync
