- hosts: all
  remote_user: root
  roles:
    - role: common
      tags: [ common ]
    - role: ssh
      tags: [ ssh ]
    - role: ldap
      when: "'admin' in group_names"
      tags: [ ldap ]
    - role: sssd
      tags: [ sssd ]
    # The users role must be executed on login node or on the single admin node
    # when fhpc_emulator_mode is enabled.
    - role: users
      when: fhpc_emulator_mode or "login" in group_names
      tags: [ users ]
    - role: slurm
      tags: [ slurm ]
    - role: slurmweb
      when:
      - "'admin' in group_names"
      - slurmweb_enabled
      tags: [ slurmweb ]
    - role: mpi
      when: mpi_nodes
      tags: [ mpi ]
