- hosts: all
  remote_user: root
  roles:
    - role: common
      tags: [ common ]
    - role: ssh
      tags: [ ssh ]

- hosts: admin
  remote_user: root
  roles:
    - role: ldap
      tags: [ ldap ]

- hosts: all
  remote_user: root
  roles:
    - role: sssd
      tags: [ sssd ]

- hosts: admin:login
  remote_user: root
  roles:
    # The users role must be executed on login node or on the single admin node
    # when fhpc_emulator_mode is enabled.
    - role: users
      when: fhpc_emulator_mode or "login" in group_names
      tags: [ users ]

- hosts: all
  remote_user: root
  roles:
    - role: slurm
      tags: [ slurm ]
    - role: racksdb
      tags: [ racksdb ]
    - role: clustershell
      tags: [ clustershell ]

- hosts: admin
  remote_user: root
  roles:
    - role: slurmweb
      when:
      - slurmweb_enabled
      tags: [ slurmweb ]
    - role: metrics
      when:
      - metrics_enabled
      tags: [ metrics ]

- hosts: login:compute
  remote_user: root
  roles:
    - role: mpi
      tags: [ mpi ]
