---
- name: Gather OS specific variables
  ansible.builtin.include_vars:
    file: "os/{{ ansible_facts.os_family | lower }}.yml"

- name: Install MariaDB and requirements
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ mariadb_packages }}"

# This is required on redhat based distributions as the service is not
# automatically started by the RPM packages.
- name: Ensure MariaDB service is started
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Create mariadb users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password | mandatory }}"
    priv: "{{ item.priv }}"
    state: present
    login_unix_socket: "{{ mariadb_socket }}"
  with_items: "{{ mariadb_users }}"
