#!/bin/bash
# Copyright (c) 2023 Rackslab
#
# This file is part of FireHPC.
#
# SPDX-License-Identifier: GPL-3.0-or-later

IFS=":" read -r CLUSTER MACHINE <<< "${1}"

# Note that --resolv-conf=replace-stub is required for applications (eg. sssd)
# that directly perform DNS requests instead of going through NSS stack for host
# service a so all applications get the same results from systemd-resolved
# daemon.
#
# Limit network zone name to the first 12 characters of cluster name to avoid
# systemd-nspawn reaching limit of 16 characters with vz- prefix that eventually
# cause 'Network zone name not valid' error.

CMD="systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-zone=${CLUSTER:0:12} --settings=override --machine=${MACHINE}.${CLUSTER} --bind=/var/lib/firehpc/${CLUSTER}/home:/home --resolv-conf=replace-stub"

exec $CMD
