#!/bin/bash

IFS=":" read -r ZONE MACHINE <<< "${1}"

CMD="systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-zone=${ZONE} --settings=override --machine=${MACHINE}.${ZONE} --bind=/var/lib/firehpc/${ZONE}/home:/home"

exec $CMD
