#!/bin/bash
# Copyright (c) 2023 Rackslab
#
# This file is part of FireHPC.
#
# SPDX-License-Identifier: GPL-3.0-or-later

ACTION=${1}
CLUSTER=${2}
CLUSTER_DIR=/var/lib/firehpc/${CLUSTER}

if [ $ACTION == "start" ]; then
    if [ ! -d ${CLUSTER_DIR} ]; then
        mkdir ${CLUSTER_DIR}
    fi
    if [ ! -d ${CLUSTER_DIR}/home ]; then
        mkdir ${CLUSTER_DIR}/home
    fi
elif [ $ACTION == "stop" ]; then
    rm -rf ${CLUSTER_DIR}
else
    logger --tag firehpc-storage-wrapper --priority local0.error unsupported action ${ACTION}
fi
