#!/bin/bash

ACTION=${1}
ZONE=${2}
ZONE_DIR=/var/lib/firehpc/${ZONE}

if [ $ACTION == "start" ]; then
    mkdir ${ZONE_DIR} ${ZONE_DIR}/home
elif [ $ACTION == "stop" ]; then
    rm -rf ${ZONE_DIR}
else
    logger --tag firehpc-storage-wrapper --priority local0.error unsupported action ${ACTION}
fi

