#!/bin/bash

ACTION=${1}
CLUSTER=${2}
CLUSTER_DIR=/var/lib/firehpc/${CLUSTER}

if [ $ACTION == "start" ]; then
    mkdir ${CLUSTER_DIR} ${CLUSTER_DIR}/home
elif [ $ACTION == "stop" ]; then
    rm -rf ${CLUSTER_DIR}
else
    logger --tag firehpc-storage-wrapper --priority local0.error unsupported action ${ACTION}
fi
