---
- name: Gather OS specific variables
  ansible.builtin.include_vars:
    file: "os/{{ ansible_facts.os_family | lower }}.yml"

- name: Set a hostname specifying strategy
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Include OS specific tasks"
  ansible.builtin.include_tasks: "os/{{ ansible_facts.os_family | lower }}.yml"

- name: Ensure basic packages are installed and updated
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: latest

- name: Define hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644

- name: Deploy CA certificate
  ansible.builtin.copy:
    src: "{{ common_local_ca_cert_file }}"
    dest: "{{ common_ca_system_dir }}/{{ common_local_ca_cert_file | basename }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Update CA certificates

- name: Include OS Rackslab repos tasks"
  ansible.builtin.include_tasks: "os/{{ ansible_facts.os_family | lower }}-rackslab-repos.yml"

- name: Include OS specific post tasks
  ansible.builtin.include_tasks: "os/{{ ansible_facts.os_family | lower }}-post.yml"
