---
- name: Gather OS specific variables
  ansible.builtin.include_vars:
    file: "os/{{ ansible_facts.os_family | lower }}.yml"

- name: Set a hostname specifying strategy
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Include OS specific tasks"
  ansible.builtin.include_tasks: "os/{{ ansible_facts.os_family | lower }}.yml"

- name: Ensure basic packages are installed and updated
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"
