---
- name: Gather OS specific variables
  ansible.builtin.include_vars:
    file: "os/{{ ansible_facts.os_family | lower }}.yml"

- name: Install redis packages
  ansible.builtin.package:
    name: "{{ redis_packages }}"
    state: latest

- name: Comment restricted bind line
  ansible.builtin.lineinfile:
    path: "{{ redis_conf_file }}"
    regexp: 'bind 127.0.0.1(.*)'
    line: '# bind 127.0.0.1\1'
    backrefs: yes
  notify:
  - Restart redis

- name: Add requirepass
  ansible.builtin.lineinfile:
    path: "{{ redis_conf_file }}"
    regexp: 'requirepass \+$'
    line: "requirepass {{ redis_password }}"
  notify:
  - Restart redis

- name: Ensure Redis is started and enabled
  ansible.builtin.systemd_service:
    name: "{{ redis_service }}"
    state: started
    enabled: true
