---
- name: Deploy SSH root keys on admin node
  ansible.builtin.copy:
    src: "{{ ssh_key_dir }}/{{ item }}"
    dest: "/root/.ssh/{{ item }}"
    owner: root
    group: root
    mode: '0600'
  loop:
  - id_rsa
  - id_rsa.pub
  when: "'admin' in group_names"

- name: Deploy SSH system known_hosts
  ansible.builtin.copy:
    src: "{{ ssh_key_dir }}/known_hosts"
    dest: "/etc/ssh/ssh_known_hosts"
    owner: root
    group: root
    mode: 0644
