---
- name: Ensure OpenSSH daemon is installed
  ansible.builtin.apt:
    name: openssh-server
    state: latest

- name: Deploy SSH host public keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ item | basename}}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "{{ ssh_key_dir }}/hosts/{{ inventory_hostname }}/ssh_host_*_key.pub"
  notify:
    - Restart SSH server

- name: Deploy SSH host private keys
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ item | basename}}"
    owner: root
    group: root
    mode: '0600'
  with_fileglob:
    - "{{ ssh_key_dir }}/hosts/{{ inventory_hostname }}/ssh_host_*_key"
  notify:
    - Restart SSH server

- name: Create root personal SSH directory
  ansible.builtin.file:
    path: "/root/.ssh"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Deploy SSH root authorized_keys
  ansible.builtin.copy:
    src: "{{ ssh_key_dir }}/id_rsa.pub"
    dest: "/root/.ssh/authorized_keys"
    owner: root
    group: root
    mode: '0600'

- name: Deploy SSH system known_hosts
  ansible.builtin.copy:
    src: "{{ ssh_key_dir }}/known_hosts"
    dest: "/etc/ssh/ssh_known_hosts"
    owner: root
    group: root
    mode: 0644
