---
ldap_packages: "{{ [ ldap_server_package ] + ldap_extra_packages }}"
ldap_base: "dc=cluster,dc=local"  # dummy
ldap_user_password: secret
ldap_email_domain: cluster.local  # dummy
ldap_users: []  # dummy
ldap_groups: []  # dummy
ldap_local_admin_password_file:  ldap.password  # dummy
# The lookup errors are ignored because the variable is loaded by boostrap
# tasks file (in bootstrap playbook) before it generates the file. This way, a
# warning is displayed but Ansible continues instead of failing with the error.
ldap_admin_password: "{{ lookup('file', '{{ ldap_local_admin_password_file }}', errors='ignore') }}"
ldap_domain: cluster.local  # dummy
ldap_ldif_path: /tmp/bootstrap.ldif
ldap_first_uid: 10001
ldap_first_gid: 10001
ldap_local_ca_dir: ca  # dummy
ldap_server_hostname: admin  # dummy
ldap_local_ca_password_file: "{{ ldap_local_ca_dir }}/ca.password"
ldap_local_ca_key_file: "{{ ldap_local_ca_dir }}/key.pem"
ldap_local_ca_cert_file: "{{ ldap_local_ca_dir }}/ca.crt"
ldap_local_tls_key_file: "{{ ldap_local_ca_dir }}/key-ldap.pem"
ldap_local_tls_cert_file: "{{ ldap_local_ca_dir }}/cert-ldap.crt"

ldap_tls_dir: /etc/ldap/tls
ldap_tls_ca_cert_file: "{{ ldap_tls_dir }}/ca.crt"
ldap_tls_cert_file: "{{ ldap_tls_dir }}/cert.crt"
ldap_tls_key_file: "{{ ldap_tls_dir }}/key.pem"
