---
- name: Create main group of users
  ansible.builtin.group:
    name: "{{ users_group }}"
    gid: "{{ users_gid }}"

- name: Create users
  user:
    name: "{{ item.login }}"
    comment: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ users_group }}"
    shell: /bin/bash
  with_items: "{{ users_defs }}"

# Generate users SSH keys and authorized_keys. It operates on front node only
# as the /home is shared between nodes.

- name: Create user SSH directory
  ansible.builtin.file:
    path: "/home/{{ item.login }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ item.login }}"
    group: "{{ users_group }}"
  with_items: "{{ users_defs }}"
  when: inventory_hostname == 'front'

- name: Generate internal SSH keys
  community.crypto.openssh_keypair:
    path: "/home/{{ item.login }}/.ssh/id_rsa"
    type: "rsa"
    mode: 0700
    owner: "{{ item.login }}"
    group: "{{ users_group }}"
  with_items: "{{ users_defs }}"
  when: inventory_hostname == 'front'

- name: Read generated users SSH public keys
  ansible.builtin.slurp:
    src: "/home/{{ item.login }}/.ssh/id_rsa.pub"
  register: users_ssh_pubkeys
  with_items: "{{ users_defs }}"
  when: inventory_hostname == 'front'

- name: Add user internal SSH key to authorized_keys
  ansible.posix.authorized_key:
     user: "{{ item.item.login }}"
     state: present
     key: "{{ item.content | b64decode }}"
  loop: "{{ users_ssh_pubkeys.results }}"
  when: inventory_hostname == 'front'

# Deploy SSH key generated on host in all users authorized_keys to easily
# connect as users from host.

- name: Add host SSH public key to all users authorized_keys
  ansible.posix.authorized_key:
     user: "{{ item.login }}"
     state: present
     key: "{{ lookup('file', '{{ users_ssh_host_key_dir }}/id_rsa.pub') }}"
  when: inventory_hostname == 'front'
  with_items: "{{ users_defs }}"
