---
- name: Debian specific pre-installation tasks
  block:
  - name: Define LDAP server organization domain
    ansible.builtin.debconf:
      name: slapd
      question: "slapd/domain"
      value: "{{ ldap_domain }}"
      vtype: string

  - name: Define LDAP server administration password
    ansible.builtin.debconf:
      name: slapd
      question: "{{ item }}"
      value: "{{ ldap_admin_password }}"
      vtype: password
    loop:
    - slapd/password1
    - slapd/password2
  when:
  # Run this block of tasks in pre-install phase only if ldap server package is
  # not installed yet. It is pointless to define these debconf parameters if
  # LDAP server package is already installed.
  - ldap_phase == 'pre_install'
  - ldap_server_package not in ansible_facts.packages

- name: Debian specific post-installation tasks
  block:
  - name: Ensure LDAP server listens for ldaps protocol
    ansible.builtin.lineinfile:
      path: /etc/default/slapd
      regexp: '^SLAPD_SERVICES='
      line: SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///"
    notify: Restart slapd
  when:
  - ldap_phase == 'post_install'
