# shared variables
fhpc_local_ssh_dir: "{{ fhpc_zone_state_dir }}/ssh"
fhpc_users_group: scientists

# roles variables
common_local_ca_dir: "{{ fhpc_zone_state_dir }}/ca"
ssh_key_dir: "{{ fhpc_local_ssh_dir }}"
ldap_local_admin_password_file: "{{ fhpc_zone_state_dir }}/ldap/ldap.password"
ldap_base: "dc=cluster,dc={{ fhpc_zone }}"
ldap_domain: "cluster.{{ fhpc_zone }}"
ldap_email_domain: "cluster.{{ fhpc_zone }}"
ldap_users: "{{ fhpc_users }}"
ldap_users_group: "{{ fhpc_users_group }}"
sssd_ldap_base: "dc=cluster,dc={{ fhpc_zone }}"
sssd_ldap_server: admin
users_ssh_host_key_dir: "{{ fhpc_local_ssh_dir }}"
users_defs: "{{ fhpc_users }}"
users_group: "{{ fhpc_users_group }}"
slurm_local_munge_key_file: "{{ fhpc_zone_state_dir }}/munge/munge.key"
slurm_local_mariadb_password_file: "{{ fhpc_zone_state_dir }}/mariadb/mariadb.password"
slurm_local_jwt_key_file: "{{ fhpc_zone_state_dir }}/slurm/jwt_hs256.key"
slurm_users: "{{ fhpc_users | map(attribute='login') | list }}"
slurm_account: "{{ fhpc_users_group }}"
