# shared variables
fhpc_local_ssh_dir: "{{ fhpc_zone_state_dir }}/ssh"
fhpc_users:
  - { login: "marie",  name: "Marie Curie",  uid: 10001 }
  - { login: "pierre", name: "Pierre Curie", uid: 10002 }

# roles variables
ssh_key_dir: "{{ fhpc_local_ssh_dir }}"
ldap_server_local_admin_password_file: "{{ fhpc_zone_state_dir }}/ldap/ldap.password"
ldap_base: "dc=cluster,dc={{ fhpc_zone }}"
ldap_server_domain: "cluster.{{ fhpc_zone }}"
ldap_email_domain: "cluster.{{ fhpc_zone }}"
sssd_ldap_base: "dc=cluster,dc={{ fhpc_zone }}"
sssd_ldap_server: admin
users_ssh_host_key_dir: "{{ fhpc_local_ssh_dir }}"
users_defs: "{{ fhpc_users }}"
slurm_local_munge_key_file: "{{ fhpc_zone_state_dir }}/munge/munge.key"
slurm_local_mariadb_password_file: "{{ fhpc_zone_state_dir }}/mariadb/mariadb.password"
slurm_users: "{{ fhpc_users | map(attribute='login') | list }}"
