# shared variables
fhpc_local_ssh_dir: "{{ fhpc_cluster_state_dir }}/ssh"
fhpc_local_ca_dir: "{{ fhpc_cluster_state_dir }}/ca"
fhpc_ldap_server: "{{ groups['admin'][0] }}"
fhpc_ldap_base: "dc=cluster,dc={{ fhpc_cluster }}"
fhpc_primary_group: "{{ fhpc_groups[0].name }}"
fhpc_slurmrestd_socket: /run/slurmrestd/slurmrestd.socket

# roles variables
common_local_ca_dir: "{{ fhpc_local_ca_dir }}"
common_ip_addresses: "{{ fhpc_addresses }}"
common_cluster: "{{ fhpc_cluster }}"
ssh_key_dir: "{{ fhpc_local_ssh_dir }}"
ldap_local_ca_dir: "{{ fhpc_local_ca_dir }}"
ldap_server_hostname: "{{ fhpc_ldap_server }}"
ldap_local_admin_password_file: "{{ fhpc_cluster_state_dir }}/ldap/ldap.password"
ldap_base: "dc=cluster,dc={{ fhpc_cluster }}"
ldap_domain: "cluster.{{ fhpc_cluster }}"
ldap_email_domain: "cluster.{{ fhpc_cluster }}"
ldap_users: "{{ fhpc_users }}"
ldap_groups: "{{ fhpc_groups }}"
sssd_ldap_base: "{{ fhpc_ldap_base }}"
sssd_ldap_server: "{{ fhpc_ldap_server }}"
users_ssh_host_key_dir: "{{ fhpc_local_ssh_dir }}"
users_defs: "{{ fhpc_users }}"
users_group: "{{ fhpc_primary_group }}"
slurm_emulator: "{{ fhpc_emulator_mode }}"
slurm_server: "{{ groups['admin'][0] }}"
# This hash associates slurm profiles in keys with a group of nodes on which the
# the profile must be applied when slurm_emulator is false. When slurm_emulator
# is true, all slurm profiles are applied on the single admin node.
slurm_profiles:
  compute: compute
  server: admin
slurm_local_munge_key_file: "{{ fhpc_cluster_state_dir }}/munge/munge.key"
slurm_local_mariadb_password_file: "{{ fhpc_cluster_state_dir }}/mariadb/mariadb.password"
slurm_local_jwt_key_file: "{{ fhpc_cluster_state_dir }}/slurm/jwt_hs256.key"
slurm_users: "{{ fhpc_users | map(attribute='login') | list }}"
slurm_restd_socket: "{{ fhpc_slurmrestd_socket }}"
slurm_accounts: "{{ fhpc_groups }}"
slurm_compute_nodes: "{{ fhpc_nodes['compute'] }}"
racksdb_database: "{{ fhpc_db }}"
redis_local_password_file: "{{ fhpc_cluster_state_dir }}/redis/redis.password"
slurmweb_slurmrestd_socket: "{{ fhpc_slurmrestd_socket }}"
slurmweb_agent_settings_defaults:
  service:
    cluster: "{{ fhpc_cluster }}"
  slurmrestd:
    socket: "{{ fhpc_slurmrestd_socket }}"
  cache:
    enabled: yes
    password: "{{ lookup('ansible.builtin.file', redis_local_password_file) }}"
slurmweb_gateway_settings_defaults:
  ui:
    host: "http://{{ slurmweb_hostname }}"
  agents:
    url: "http://{{ slurmweb_hostname }}/{{ slurmweb_agent_subdir }}"
  authentication:
    enabled: yes
  ldap:
    uri: "ldaps://{{ fhpc_ldap_server }}/"
    user_base: "ou=people,{{ fhpc_ldap_base }}"
    group_base: "ou=groups,{{ fhpc_ldap_base }}"
