# shared variables
fhpc_local_ssh_dir: '../../ssh'

# roles variables
ssh_key_dir: "{{ fhpc_local_ssh_dir }}"
users_ssh_host_key_dir: "{{ fhpc_local_ssh_dir }}"
slurm_local_munge_dir: ../../local/munge
slurm_db_password: secret
