= fhpc-emulate-slurm-usage(1)
Rackslab: https://rackslab.io
:doctype: manpage
:manmanual: fhpc-emulate-slurm-usage
:man-linkstyle: pass:[blue R < >]

== Name

fhpc-emulate-slurm-usage - Emulate real usage of Slurm on FireHPC clusters

== Synopsis

[.cli-opt]#*fhpc-emulate-slurm-usage*# `[_GENERAL OPTIONS_] CLUSTER [CLUSTER …]`

== Description

This utility emulates real cluster usage by submitting random Slurm jobs with
all users accounts on FireHPC emulated clusters.

Multiple cluster names can be provided in arguments, `fhpc-emulate-slurm-usage`
launches jobs on clusters in parallel.

== General Options

[.cli-opt]#*-h, --help*#::
  Show this help message and exit.

[.cli-opt]#*-v, --version*#::
  Show FireHPC version number and exit.

[.cli-opt]#*--debug*#::
  Enable debug mode with more messages in output.

[.cli-opt]#*--show-libs-logs*#::
  Show external libraries logs additionally to FireHPC internal logs.

[.cli-opt]#*--state*=#[.cli-optval]##_STATE_##::
  Path to FireHPC state directory where generated files (keys, certificates,
  users, etc) are stored before deployment in containers. Default value is
  [.path]#`~/.local/state/firehpc`#. If _$XDG_STATE_HOME_ environment variable
  is defined, its value appended with _firehpc_ subfolder is considered the new
  default.

== Exit status

*0*::
  `fhpc-emulate-slurm-usage` has processed command with success.

*1*::
  `fhpc-emulate-slurm-usage` encountered an error.

== Resources

FireHPC web site: https://github.com/rackslab/firehpc

== Copying

Copyright (C) 2023 {author}. +

FireHPC is distributed under the terms of the GNU General Public License v3.0
or later (GPLv3+).
