---
- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: Restart alloy
  ansible.builtin.service:
    name: alloy
    state: restarted
